### ISSUE TITLE
KSP 1.3.1 crash

### ISSUE THREAD

**Issue by LouisCyfer** [Alshain01/ActionGroupManager#5] opened 2017-10-12 21:11 UTC
I know it should be working according to your [ActionGroupManager.version](https://github.com/Alshain01/ActionGroupManager/blob/master/ActionGroupManager/ActionGroupManager.version) but v2.2 crashes KSP 1.3.1

KSP.log doesnt show up anything but when I uninstall AGM KSP loads up perfectly :/

Would be amazing if you update and/or recompile or fix that issue.

**Comment by Real-Gecko** [comment] 2017-10-16 19:47
Recompiling `AGM-LiteUI.dll` and `ActionGroupManager.dll` does not solve the problem.
Crash caused by `AGM-VisualUI.dll`, only after recompiling it game starts flawlessly.

**Comment by Alshain01** [comment] 2017-10-23 13:17
Fixed in 2.2.1

**Closed as completed by Alshain01** 2017-10-23 13:17 UTC
